Added Components
innerkorehq/innerkore-design-system pull request #1
Opened 2021-03-24 06:39 UTC by Pradhumn07

2021-03-24 07:51 UTC, instagagan requested changes
- Add Comments, more appropriately.
- ClassName argument is missing from all the components.
- Format your code, use visual studio code extension Prettier.
- code is not responsive
- No hardcoded value in components

2021-03-24 07:51 UTC, instagagan commented on src/components/DataList.tsx
> +        <option value="Mumbai"/>
No hardcoded value in components

2021-03-29 18:33 UTC, gagandeep commented on package.json
> +    "@storybook/react": "^6.1.21",
This is the problem with your setup.

2021-04-09 14:14 UTC, gagandeep approved these changes

2021-04-09 14:14 UTC, merged